spring:
  datasource:
    url: jdbc:mariadb://ifsp-mariadb:3306/activity_db
    username: cora_user
    password: user_password
    driver-class-name: org.mariadb.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    preferIpAddress: true